import type {Metadata} from "next"; import Link from "next/link"; import {notFound} from "next/navigation";
import {PriceChart} from "@/components/price-chart"; import {marketDetail} from "@/lib/market-repository";
type Props={params:Promise<{stableId:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const m=await marketDetail(decodeURIComponent((await params).stableId));return{title:m?.itemName??"Market not found"}}
const price=(v:number|undefined)=>v==null?"—":`${v.toLocaleString(undefined,{maximumFractionDigits:2})} keys`;
export default async function MarketPage({params}:Props){const m=await marketDetail(decodeURIComponent((await params).stableId));if(!m)notFound();const first=m.history[0],latest=m.history.at(-1),movement=first&&latest?(latest.priceKeys-first.priceKeys)/first.priceKeys*100:null;
return <main><Link href="/" className="back">← Back to market search</Link><section className="detail"><div><div className="tags"><span>{m.dataset}</span><span>{m.effectName??m.quality}</span></div><h1>{m.itemName}</h1><p className="id">{m.stableId}</p></div><aside className="current"><small>Latest guide price</small><strong>{price(latest?.priceKeys)}</strong><span>{latest?new Date(latest.collectedAt).toLocaleDateString():"No priced observations"}</span></aside></section>
<section className="metrics"><article><small>Observations</small><strong>{m.history.length}</strong><span>priced snapshots</span></article><article><small>Full-period movement</small><strong className={movement!=null&&movement<0?"down":"up"}>{movement==null?"—":`${movement>=0?"+":""}${movement.toFixed(1)}%`}</strong><span>first to latest</span></article><article><small>First recorded</small><strong>{new Date(m.firstSeenAt).toLocaleDateString()}</strong><span>{price(first?.priceKeys)}</span></article></section>
<section className="chart-panel"><div className="section-title"><div><p className="eyebrow">PRICE HISTORY</p><h2>Guide price in keys</h2></div><span>Hover over a point for its value</span></div><PriceChart points={m.history}/></section><section className="note"><strong>How to read this</strong><p>These are community guide prices captured by the daily pipeline. They are historical reference points, not completed sale prices.</p></section></main>}
