CREATE TABLE IF NOT EXISTS snapshots (
  snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset TEXT NOT NULL CHECK (dataset IN ('unusual','community')),
  collected_at TEXT NOT NULL,
  source_file TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  cleaning_version TEXT,
  validation_status TEXT NOT NULL DEFAULT 'validated'
    CHECK (validation_status IN ('validated','legacy_unverified')),
  imported_at TEXT NOT NULL,
  market_count INTEGER NOT NULL CHECK (market_count >= 0),
  priced_observation_count INTEGER NOT NULL
    CHECK (priced_observation_count BETWEEN 0 AND market_count),
  quality_report_json JSONB,
  UNIQUE (dataset,collected_at), UNIQUE (dataset,source_sha256)
);
CREATE TABLE IF NOT EXISTS markets (
  market_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stable_id TEXT NOT NULL UNIQUE,
  dataset TEXT NOT NULL CHECK (dataset IN ('unusual','community')),
  defindex INTEGER, effect_id INTEGER, item_name TEXT NOT NULL,
  effect_name TEXT, quality TEXT, craftable BOOLEAN, tradable BOOLEAN NOT NULL DEFAULT TRUE,
  item_type TEXT, slot TEXT, summary TEXT, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL,
  CHECK ((dataset='unusual' AND defindex IS NOT NULL AND effect_id IS NOT NULL)
      OR (dataset='community' AND quality IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS price_observations (
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(snapshot_id) ON DELETE CASCADE,
  market_id BIGINT NOT NULL REFERENCES markets(market_id),
  price_ref DOUBLE PRECISION NOT NULL CHECK (price_ref > 0),
  price_keys DOUBLE PRECISION NOT NULL CHECK (price_keys > 0),
  price_usd DOUBLE PRECISION CHECK (price_usd >= 0),
  key_price_ref DOUBLE PRECISION CHECK (key_price_ref > 0),
  source_price_low DOUBLE PRECISION CHECK (source_price_low > 0),
  source_price_high DOUBLE PRECISION CHECK (source_price_high >= source_price_low),
  source_price_unit TEXT CHECK (source_price_unit IN ('ref','keys') OR source_price_unit IS NULL),
  source_updated_at TEXT, source_price_provenance TEXT, key_rate_source TEXT,
  price_is_range BOOLEAN, quality_flags TEXT,
  raw_row_number INTEGER CHECK (raw_row_number >= 2 OR raw_row_number IS NULL),
  PRIMARY KEY (snapshot_id,market_id)
);
CREATE TABLE IF NOT EXISTS current_prices (
  market_id BIGINT PRIMARY KEY REFERENCES markets(market_id),
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(snapshot_id) ON DELETE CASCADE,
  price_ref DOUBLE PRECISION NOT NULL CHECK (price_ref > 0),
  price_keys DOUBLE PRECISION NOT NULL CHECK (price_keys > 0),
  price_usd DOUBLE PRECISION CHECK (price_usd >= 0),
  key_price_ref DOUBLE PRECISION CHECK (key_price_ref > 0),
  source_price_low DOUBLE PRECISION CHECK (source_price_low > 0),
  source_price_high DOUBLE PRECISION CHECK (source_price_high >= source_price_low),
  source_price_unit TEXT CHECK (source_price_unit IN ('ref','keys') OR source_price_unit IS NULL),
  source_updated_at TEXT, source_price_provenance TEXT, key_rate_source TEXT,
  price_is_range BOOLEAN, quality_flags TEXT,
  raw_row_number INTEGER CHECK (raw_row_number >= 2 OR raw_row_number IS NULL)
);
-- A priced observation already proves that a market was present.  Store only
-- the uncommon unpriced rows here and expose the full SQLite-compatible shape
-- through the market_presence view below.  This avoids duplicating millions of
-- keys in the hosted database.
CREATE TABLE IF NOT EXISTS unpriced_market_presence (
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(snapshot_id) ON DELETE CASCADE,
  market_id BIGINT NOT NULL REFERENCES markets(market_id),
  quality_flags TEXT, raw_row_number INTEGER CHECK (raw_row_number >= 2 OR raw_row_number IS NULL),
  PRIMARY KEY (snapshot_id,market_id)
);
CREATE TABLE IF NOT EXISTS snapshot_quality_issues (
  snapshot_id BIGINT NOT NULL REFERENCES snapshots(snapshot_id) ON DELETE CASCADE,
  issue_code TEXT NOT NULL, issue_kind TEXT NOT NULL CHECK (issue_kind IN ('warning','rejection')),
  affected_rows INTEGER NOT NULL CHECK (affected_rows >= 0),
  PRIMARY KEY (snapshot_id,issue_kind,issue_code)
);
CREATE OR REPLACE VIEW market_presence AS
SELECT snapshot_id, market_id, 'priced'::TEXT AS price_status,
       quality_flags, raw_row_number
FROM price_observations
UNION ALL
SELECT snapshot_id, market_id, 'unpriced'::TEXT AS price_status,
       quality_flags, raw_row_number
FROM unpriced_market_presence;
